# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.
[libraries]
work.files = [
    'double_ff_pkg.vhd',
    'double_ff.vhd',
    'clock_divider_pkg.vhd',
    'clock_divider.vhd',
    'testbench_clock_divider.vhd',
    'blink_LED_1_pkg.vhd',
    'blink_LED_1.vhd',
    'testbench_blink_LED_1.vhd'
]
